// components/general/BackToTopButton.vue
<template>
  <transition name="fade-up">
    <div
      v-show="isVisible"
      @click="scrollToTop"
      class="fixed bottom-[186px] right-[5%] p-3 bg-[#EEE4D9]/30 backdrop-blur-md flex items-center justify-center rounded-full shadow-lg cursor-pointer transition-opacity duration-300 hover:backdrop-blur-xl hover:shadow-xl"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 19 19"
        fill="none"
        class="stroke-[#88735F]"
      >
        <path
          d="M5.44042 11.7702L9.90851 7.30212L14.3766 11.7702"
          stroke="#88735F"
          stroke-width="1.78723"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </div>
  </transition>
</template>
<script setup lang="ts">
const nuxtApp = useNuxtApp()
const isVisible = ref(false)

const toggleVisibility = () => {
  if (window.scrollY > 250) {
    isVisible.value = true
  } else {
    isVisible.value = false
  }
}

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: 'smooth',
  })
}

nuxtApp.hook('app:mounted', () => {
  window.addEventListener('scroll', toggleVisibility)
})

onUnmounted(() => {
  window.removeEventListener('scroll', toggleVisibility)
})
</script>

<style scoped>
.fade-up-enter-active, .fade-up-leave-active {
  @apply transition-all duration-300 ease-out;
}
.fade-up-enter-from {
  @apply opacity-0 translate-y-5;
}
.fade-up-enter-to {
  @apply opacity-100 translate-y-0;
}
.fade-up-leave-from {
  @apply opacity-100 translate-y-0;
}
.fade-up-leave-to {
  @apply opacity-0 translate-y-5;
}
</style>

// components/layout/back-to-top-button.tsx
'use client'

import { useState, useEffect } from 'react'
import { ChevronUp } from 'lucide-react'

export default function BackToTopButton() {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setVisible(window.scrollY > 300)
    }
    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <button
      type="button"
      onClick={scrollToTop}
      className={`fixed bottom-5 right-4 z-40 flex h-11 w-11 cursor-pointer items-center justify-center rounded-full bg-white/80 text-sandrift-500 ring-1 ring-sandrift-200/30 shadow-[0_2px_12px_rgba(176,141,98,0.08)] backdrop-blur-xl transition-all duration-300 hover:text-sandrift-800 hover:shadow-[0_4px_16px_rgba(176,141,98,0.15)] lg:bottom-8 lg:right-8 ${
        visible
          ? 'scale-100 opacity-100'
          : 'pointer-events-none scale-90 opacity-0'
      }`}
      aria-label="回到頂部"
    >
      <ChevronUp className="h-5 w-5" strokeWidth={1.5} />
    </button>
  )
}
