// components/product-card.tsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import CartStepperButton from '@/components/cart-stepper-button'
import type { ProductInfo } from '@/types'

const cardBgs = [
  '/images/products/common/card_bg.png',
  '/images/products/common/card_bg1.png',
  '/images/products/common/card_bg2.png',
]

interface ProductCardProps {
  product: ProductInfo
  index?: number
}

export default function ProductCard({ product, index }: ProductCardProps) {
  return (
    <div className="group relative rounded-2xl bg-white ring-1 ring-sandrift-100/80 transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_8px_24px_rgba(176,141,98,0.08)]">
      <Link
        href={`/products/${product.key}`}
        className="block overflow-hidden rounded-2xl"
      >
        {/* Tag Badge */}
        {product.tag && (
          <div className="absolute right-1.5 top-1.5 z-10">
            <Image
              src={`/images/products/tags/${product.tag}.png`}
              alt={product.tag}
              width={60}
              height={36}
              className="h-auto w-10 drop-shadow-sm"
            />
          </div>
        )}

        {/* Product Image */}
        <div className="relative aspect-4/5 overflow-hidden">
          <Image
            src={cardBgs[(index ?? 0) % 3]}
            alt=""
            fill
            sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw"
            className="object-cover"
          />
          <Image
            src={product.banner.src}
            alt={product.banner.altText || product.name}
            title={product.banner.title || product.name}
            width={300}
            height={300}
            className="absolute inset-0 m-auto h-auto w-4/5 object-contain transition-transform duration-500 ease-out group-hover:scale-110"
          />
        </div>

        {/* Product Info */}
        <div className="px-3 py-2.5 sm:px-3.5 sm:py-3">
          {/* 名稱 + alias */}
          <div className="flex items-baseline gap-1.5">
            <h3 className="line-clamp-1 text-[13px] font-semibold text-sandrift-900">
              {product.name}
            </h3>
            {product.alias && (
              <span className="shrink-0 text-[10px] text-sandrift-400">
                {product.alias}
              </span>
            )}
          </div>

          {/* 價格 + 加購按鈕 */}
          <div className="mt-1 flex items-center justify-between">
            <div className="flex items-baseline gap-1.5">
              {product.originalPrice && product.originalPrice > product.price && (
                <span className="text-[11px] text-sandrift-300 line-through">
                  ${product.originalPrice}
                </span>
              )}
              <span className="text-[14px] font-bold text-sandrift-600">
                ${product.price}
                <span className="text-[11px] font-normal text-sandrift-400">
                  /{product.unit}
                </span>
              </span>
            </div>
          </div>
        </div>
      </Link>

      {/* Cart Stepper Button — 視覺對齊價格行右側 */}
      <div className="absolute bottom-1.5 right-1.5 z-20 sm:bottom-2 sm:right-2">
        <CartStepperButton product={product} />
      </div>
    </div>
  )
}

// components/ProductCard.vue
<script setup lang="ts">
const props = defineProps({
  node: { type: Object, required: true },
})

const img = useImage();
const tagUrl = img(`/images/products/tags/${props.node.tag}.png`)

const fallbackImage = '/images/logo_s.png'
</script>

<template>
  <div
    class="relative flex flex-col overflow-hidden rounded-xl w-full aspect-[0.675] shadow-[0_1.905px_10.142px_0px_rgba(185,159,133,0.2)] px-4 py-2"
  >
    <NuxtImg
      preload
      class="absolute inset-0 object-cover w-full h-full"
      src="/images/products/common/card_bg.png"
    />
    <img width="52" v-if="tagUrl" :src="tagUrl" alt="tag" class="absolute top-4 right-4 object-cover w-[28%] h-auto" />
    <NuxtImg
      width="30"
      height="30"
      placeholder
      placeholder-class="blur-xl rounded-full"
      class="absolute bottom-[22%] right-[13px] object-cover w-[30px] h-[30px]"
      src="/images/products/common/cart.png"
    />
    <div class="relative w-full aspect-[4/5]">
      <NuxtImg
        width="264"
        :height="Math.round(264 * 1.378)"
        class="absolute bottom-[5.5%] left-1/2 transform -translate-x-1/2 object-cover w-4/5 h-auto"
        :src="node.banner?.src || fallbackImage"
        :alt="node.banner?.altText || node.name"
        :title="node.banner?.title || node.name"
        loading="lazy"
        placeholder
        placeholder-class="blur-xl"
      />
    </div>
    <span class="text-4 font-semibold text-[#4C3232]">{{ node.name }}</span>
    <UDivider class="py-1" />
    <div class="flex justify-between items-center">
      <div class="flex items-center">
        <span class="text-[#B8B8B8] font-semibold text-[12px] line-through"
          >${{ node.maxCount }}元</span
        >
        <span class="text-[#4C3232] text-4 font-semibold ml-[6px]"
          >${{ node.price }}元</span
        >
      </div>
      <div class="text-[#4C3232]/20 font-bold text-xs">{{ node.alias }}</div>
    </div>
  </div>
</template>

<style lang="postcss" scoped></style>
